[package]
name = "{{pointbreak-entry}}"
version = "0.1.0"
authors = ["{{Luciano Remes}}"]
edition = "2022"
license-file = "LICENSE-MIT.md"
readme = "README.md"

[dependencies]
clap = "3.1.3"

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
